import "@thrackle-io/forte-rules-engine/src/client/RulesEngineClient.sol";

// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.24;

/**
 * @title Institutional RWA Forte Rules Engine Integration
 * @author ChainAim
 * @dev This file defines the Rules Engine integration for institutional RWA compliance
 * @dev Modifiers will be auto-generated by the Forte SDK based on the policy file
 * @dev Covers all 14 institutional compliance rules including ZK PRET and PYUSD
 */
abstract contract InstitutionalRWAFRE is RulesEngineClient {
    
    /**
     * @dev Modifier for comprehensive institutional asset minting (RULES 01-12)
     * @param recipient Address receiving the asset
     * @param amount Number of fractions being minted
     * @param principalAmount USD value of the underlying asset
     * @param assetType Type of institutional asset (e.g., "SUPPLY_CHAIN_INVOICE")
     * @param lei 20-character Legal Entity Identifier
     * @param corporateName Official corporate name matching LEI
     */
    modifier checkRulesBeforemintInstitutionalAsset(
        address recipient, 
        uint256 amount, 
        uint256 principalAmount, 
        string memory assetType, 
        string memory lei, 
        string memory corporateName
    ) {
        bytes memory encoded = abi.encodeWithSelector(
            msg.sig,
            recipient,
            amount,
            principalAmount,
            assetType,
            lei,
            corporateName
        );
        _invokeRulesEngine(encoded);
        _;
    }
    
    /**
     * @dev Modifier for PYUSD cross-border asset minting (RULES 13-14)
     * @param recipient Address receiving the PYUSD-denominated asset
     * @param amount Number of fractions being minted
     * @param pyusdAmount PYUSD amount for the transaction
     * @param buyerCountry ISO country code for buyer
     * @param sellerCountry ISO country code for seller
     */
    modifier checkRulesBeforemintInstitutionalAssetPYUSD(
        address recipient,
        uint256 amount,
        uint256 pyusdAmount,
        string memory buyerCountry,
        string memory sellerCountry
    ) {
        bytes memory encoded = abi.encodeWithSelector(
            msg.sig,
            recipient,
            amount,
            pyusdAmount,
            buyerCountry,
            sellerCountry
        );
        _invokeRulesEngine(encoded);
        _;
    }
    
    /**
     * @dev Modifier for transfer compliance (existing rwa-demo rules)
     * @param to Address receiving the transfer
     * @param tokenId Token being transferred
     */
    modifier checkRulesBefore_update(address to, uint256 tokenId) {
        bytes memory encoded = abi.encodeWithSelector(msg.sig, to, tokenId);
        _invokeRulesEngine(encoded);
        _;
    }
    
    /**
     * @dev Post-transfer modifier (if needed for additional compliance)
     * @param to Address that received the transfer
     * @param tokenId Token that was transferred
     */
    modifier checkRulesAfter_update(address to, uint256 tokenId) {
        bytes memory encoded = abi.encodeWithSelector(msg.sig, to, tokenId);
        _;
        _invokeRulesEngine(encoded);
    }
}
